version: '3.8'
services:
  backend:
    build:
        dockerfile: DockerFile
        context: ./backend
    image: jtjendana/cs3219_otot_task_a_backend
    volumes:
        - /usr/share/cs3219_server_app/node_modules
        - ./backend:/usr/share/cs3219_server_app
    container_name: backend
    ports:
      - 9000:9000
    restart: unless-stopped
  frontend:
    build:
        dockerfile: DockerFile
        context: ./frontend
    image: jtjendana/cs3219_otot_task_a_frontend
    volumes:
        - ./frontend/public:/usr/share/nginx/html
        - ./frontend/StaticSite.conf:/etc/nginx/conf.d/StaticSite.conf
    container_name: frontend
    ports:
      - 8000:8000
    restart: unless-stopped
  nginxreverseproxy:
    build:
      dockerfile: DockerFile
      context: ./nginxreverseproxy
    image: jtjendana/cs3219_otot_task_a_nginx_reverse_proxy
    volumes:
      - ./nginxreverseproxy/default.conf:/etc/nginx/conf.d/default.conf
    container_name: ngixreverseproxy
    ports:
      - 80:80
    restart: always
    depends_on:
      - frontend
      - backend